// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShapeUp.Features.PlatformFeatureFlags.Infrastructure.Data;

#nullable disable

namespace ShapeUp.Features.PlatformFeatureFlags.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PlatformFeatureFlagsDbContext))]
    [Migration("20260910021233_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShapeUp.Features.PlatformFeatureFlags.Shared.Entities.PlatformFeatureFlag", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("PlatformFeatureFlags", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "notifications.email-enabled",
                            Enabled = true,
                            UpdatedAtUtc = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
