// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShapeUp.Features.Authorization.Shared.Data;

#nullable disable

namespace ShapeUp.Features.Authorization.Shared.Data.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    partial class AuthorizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.GroupScope", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("ScopeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupId", "ScopeId");

                    b.HasIndex("ScopeId");

                    b.ToTable("GroupScopes");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.Scope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "Subdomain", "Action")
                        .IsUnique();

                    b.ToTable("Scopes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "create",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create groups",
                            Domain = "groups",
                            Name = "groups:management:create",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 2,
                            Action = "delete",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete groups",
                            Domain = "groups",
                            Name = "groups:management:delete",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 3,
                            Action = "manage_members",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage group members",
                            Domain = "groups",
                            Name = "groups:management:manage_members",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 4,
                            Action = "manage_scopes",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage group scopes",
                            Domain = "groups",
                            Name = "groups:management:manage_scopes",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 5,
                            Action = "create",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create scopes",
                            Domain = "scopes",
                            Name = "scopes:management:create",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 6,
                            Action = "read",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read audit logs",
                            Domain = "audit",
                            Name = "audit:logs:read",
                            Subdomain = "logs"
                        });
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.UserScope", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ScopeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ScopeId");

                    b.HasIndex("ScopeId");

                    b.ToTable("UserScopes");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.GroupScope", b =>
                {
                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.Group", "Group")
                        .WithMany("Scopes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.Scope", "Scope")
                        .WithMany("Groups")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.UserGroup", b =>
                {
                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.UserScope", b =>
                {
                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.Scope", "Scope")
                        .WithMany("Users")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.User", "User")
                        .WithMany("Scopes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.Group", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.Scope", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.User", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Scopes");
                });
#pragma warning restore 612, 618
        }
    }
}
