// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShapeUp.Features.Authorization.Shared.Data;

#nullable disable

namespace ShapeUp.Features.Authorization.Shared.Data.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    partial class AuthorizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.GroupScope", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("ScopeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupId", "ScopeId");

                    b.HasIndex("ScopeId");

                    b.ToTable("GroupScopes");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.Scope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "Subdomain", "Action")
                        .IsUnique();

                    b.ToTable("Scopes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "create",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create groups",
                            Domain = "groups",
                            Name = "groups:management:create",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 2,
                            Action = "delete",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete groups",
                            Domain = "groups",
                            Name = "groups:management:delete",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 3,
                            Action = "manage_members",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage group members",
                            Domain = "groups",
                            Name = "groups:management:manage_members",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 4,
                            Action = "manage_scopes",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage group scopes",
                            Domain = "groups",
                            Name = "groups:management:manage_scopes",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 5,
                            Action = "create",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create scopes",
                            Domain = "scopes",
                            Name = "scopes:management:create",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 6,
                            Action = "read",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read audit logs",
                            Domain = "audit",
                            Name = "audit:logs:read",
                            Subdomain = "logs"
                        },
                        new
                        {
                            Id = 7,
                            Action = "assign",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assign scope",
                            Domain = "scopes",
                            Name = "scopes:management:assign",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 8,
                            Action = "sync",
                            CreatedAt = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Synchronize user scopes to Firebase claims",
                            Domain = "scopes",
                            Name = "scopes:management:sync",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 9,
                            Action = "create",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create exercises",
                            Domain = "training",
                            Name = "training:exercises:create",
                            Subdomain = "exercises"
                        },
                        new
                        {
                            Id = 10,
                            Action = "read",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read exercises",
                            Domain = "training",
                            Name = "training:exercises:read",
                            Subdomain = "exercises"
                        },
                        new
                        {
                            Id = 11,
                            Action = "update",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update exercises",
                            Domain = "training",
                            Name = "training:exercises:update",
                            Subdomain = "exercises"
                        },
                        new
                        {
                            Id = 12,
                            Action = "delete",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete exercises",
                            Domain = "training",
                            Name = "training:exercises:delete",
                            Subdomain = "exercises"
                        },
                        new
                        {
                            Id = 13,
                            Action = "suggest",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suggest exercises",
                            Domain = "training",
                            Name = "training:exercises:suggest",
                            Subdomain = "exercises"
                        },
                        new
                        {
                            Id = 14,
                            Action = "create",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create equipments",
                            Domain = "training",
                            Name = "training:equipments:create",
                            Subdomain = "equipments"
                        },
                        new
                        {
                            Id = 15,
                            Action = "read",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read equipments",
                            Domain = "training",
                            Name = "training:equipments:read",
                            Subdomain = "equipments"
                        },
                        new
                        {
                            Id = 16,
                            Action = "update",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update equipments",
                            Domain = "training",
                            Name = "training:equipments:update",
                            Subdomain = "equipments"
                        },
                        new
                        {
                            Id = 17,
                            Action = "delete",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete equipments",
                            Domain = "training",
                            Name = "training:equipments:delete",
                            Subdomain = "equipments"
                        },
                        new
                        {
                            Id = 18,
                            Action = "create",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create workout sessions",
                            Domain = "training",
                            Name = "training:workouts:create",
                            Subdomain = "workouts"
                        },
                        new
                        {
                            Id = 19,
                            Action = "read",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read workout sessions",
                            Domain = "training",
                            Name = "training:workouts:read",
                            Subdomain = "workouts"
                        },
                        new
                        {
                            Id = 20,
                            Action = "complete",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete workout sessions",
                            Domain = "training",
                            Name = "training:workouts:complete",
                            Subdomain = "workouts"
                        },
                        new
                        {
                            Id = 21,
                            Action = "read",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read training dashboard",
                            Domain = "training",
                            Name = "training:dashboard:read",
                            Subdomain = "dashboard"
                        },
                        new
                        {
                            Id = 22,
                            Action = "create_self",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create workouts for self",
                            Domain = "training",
                            Name = "training:workouts:create:self",
                            Subdomain = "workouts"
                        },
                        new
                        {
                            Id = 23,
                            Action = "create_trainer",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create workouts as trainer for trainer-client links",
                            Domain = "training",
                            Name = "training:workouts:create:trainer",
                            Subdomain = "workouts"
                        },
                        new
                        {
                            Id = 24,
                            Action = "create_gym_staff",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create workouts as gym trainer staff",
                            Domain = "training",
                            Name = "training:workouts:create:gym_staff",
                            Subdomain = "workouts"
                        },
                        new
                        {
                            Id = 25,
                            Action = "create",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create muscles",
                            Domain = "training",
                            Name = "training:muscles:create",
                            Subdomain = "muscles"
                        },
                        new
                        {
                            Id = 26,
                            Action = "read",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read muscles",
                            Domain = "training",
                            Name = "training:muscles:read",
                            Subdomain = "muscles"
                        },
                        new
                        {
                            Id = 27,
                            Action = "update",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update muscles",
                            Domain = "training",
                            Name = "training:muscles:update",
                            Subdomain = "muscles"
                        },
                        new
                        {
                            Id = 28,
                            Action = "delete",
                            CreatedAt = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete muscles",
                            Domain = "training",
                            Name = "training:muscles:delete",
                            Subdomain = "muscles"
                        },
                        new
                        {
                            Id = 29,
                            Action = "read",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read groups",
                            Domain = "groups",
                            Name = "groups:management:read",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 30,
                            Action = "read",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read scopes",
                            Domain = "scopes",
                            Name = "scopes:management:read",
                            Subdomain = "management"
                        },
                        new
                        {
                            Id = 31,
                            Action = "read",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read user profile",
                            Domain = "users",
                            Name = "users:profile:read",
                            Subdomain = "profile"
                        },
                        new
                        {
                            Id = 32,
                            Action = "read_gym_staff",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read gym clients as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:clients:read:gym_staff",
                            Subdomain = "clients"
                        },
                        new
                        {
                            Id = 33,
                            Action = "create_gym_staff",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Enroll gym clients as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:clients:create:gym_staff",
                            Subdomain = "clients"
                        },
                        new
                        {
                            Id = 34,
                            Action = "assign_trainer_gym_staff",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assign gym client trainer as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:clients:assign_trainer:gym_staff",
                            Subdomain = "clients"
                        },
                        new
                        {
                            Id = 35,
                            Action = "read_gym_plan",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read gym plans as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:plans:read",
                            Subdomain = "plans"
                        },
                        new
                        {
                            Id = 36,
                            Action = "create_gym_plan",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create gym plans as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:plans:create",
                            Subdomain = "plans"
                        },
                        new
                        {
                            Id = 37,
                            Action = "update_gym_plan",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update gym plans as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:plans:update",
                            Subdomain = "plans"
                        },
                        new
                        {
                            Id = 38,
                            Action = "delete_gym_plan",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete gym plans as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:plans:delete",
                            Subdomain = "plans"
                        },
                        new
                        {
                            Id = 39,
                            Action = "read_gym_staff",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read gyms as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:gyms:read:gym_staff",
                            Subdomain = "gyms"
                        },
                        new
                        {
                            Id = 40,
                            Action = "create_gym_staff",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create gyms as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:gyms:create:gym_staff",
                            Subdomain = "gyms"
                        },
                        new
                        {
                            Id = 41,
                            Action = "update_gym_staff",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update gyms as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:gyms:update:gym_staff",
                            Subdomain = "gyms"
                        },
                        new
                        {
                            Id = 42,
                            Action = "delete_gym_staff",
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete gyms as gym owner or staff",
                            Domain = "gym",
                            Name = "gym:gyms:delete:gym_staff",
                            Subdomain = "gyms"
                        });
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.UserScope", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ScopeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ScopeId");

                    b.HasIndex("ScopeId");

                    b.ToTable("UserScopes");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.GroupScope", b =>
                {
                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.Group", "Group")
                        .WithMany("Scopes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.Scope", "Scope")
                        .WithMany("Groups")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.UserGroup", b =>
                {
                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.UserScope", b =>
                {
                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.Scope", "Scope")
                        .WithMany("Users")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShapeUp.Features.Authorization.Shared.Entities.User", "User")
                        .WithMany("Scopes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.Group", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.Scope", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShapeUp.Features.Authorization.Shared.Entities.User", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Scopes");
                });
#pragma warning restore 612, 618
        }
    }
}
