// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShapeUp.Features.Nutrition.Infrastructure.Data;

#nullable disable

namespace ShapeUp.Features.Nutrition.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    [Migration("20261003125823_AddNutritionProfessionalTools")]
    partial class AddNutritionProfessionalTools
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.DiaryDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EvaluatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("NutritionDiaryDays", (string)null);
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.DiaryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("DiaryDayId")
                        .HasColumnType("int");

                    b.Property<string>("FoodId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("QuantityGramsOrMl")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("UsesOverride")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DiaryDayId");

                    b.ToTable("NutritionDiaryEntries", (string)null);
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.FastingAgenda", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("EatHours")
                        .HasColumnType("int");

                    b.Property<int?>("EatingStartMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("FastHours")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("RecommendedFastHours")
                        .HasColumnType("int");

                    b.Property<string>("RecommendedProtocol")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("NutritionFastingAgendas", (string)null);
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.FastingOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EatEndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EatHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("FastEndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FastHours")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[Status] IN ('Fasting', 'Eating')");

                    b.ToTable("NutritionFastingOverrides", (string)null);
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.NutritionDiaryComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<int>("ClientUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("EntryId")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId", "Date");

                    b.ToTable("NutritionDiaryComments", (string)null);
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.NutritionGoalEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GoalMet")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("NutritionGoalEvaluations", (string)null);
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.NutritionMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BodyFatPercent")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal?>("HipCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WaistCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("NutritionMeasurements", (string)null);
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.NutritionProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Allergies")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BiologicalSex")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("int");

                    b.Property<bool>("OnboardingSkipped")
                        .HasColumnType("bit");

                    b.Property<string>("Restrictions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WaterGoalMl")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("NutritionProfiles", (string)null);
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.WeightRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("NutritionWeightRegisters", (string)null);
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.WeightTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("TargetWeight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NutritionWeightTargets", (string)null);
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.DiaryEntry", b =>
                {
                    b.HasOne("ShapeUp.Features.Nutrition.Shared.Entities.DiaryDay", "DiaryDay")
                        .WithMany("Entries")
                        .HasForeignKey("DiaryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ShapeUp.Features.Nutrition.Shared.ValueObjects.MacroValueObject", "ComputedMacros", b1 =>
                        {
                            b1.Property<string>("DiaryEntryId")
                                .HasColumnType("nvarchar(24)");

                            b1.Property<int>("CarbG")
                                .HasColumnType("int")
                                .HasColumnName("ComputedMacros_CarbG");

                            b1.Property<int>("FatG")
                                .HasColumnType("int")
                                .HasColumnName("ComputedMacros_FatG");

                            b1.Property<int>("Kcal")
                                .HasColumnType("int")
                                .HasColumnName("ComputedMacros_Kcal");

                            b1.Property<int>("ProteinG")
                                .HasColumnType("int")
                                .HasColumnName("ComputedMacros_ProteinG");

                            b1.HasKey("DiaryEntryId");

                            b1.ToTable("NutritionDiaryEntries");

                            b1.WithOwner()
                                .HasForeignKey("DiaryEntryId");
                        });

                    b.Navigation("ComputedMacros")
                        .IsRequired();

                    b.Navigation("DiaryDay");
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.NutritionProfile", b =>
                {
                    b.OwnsOne("ShapeUp.Features.Nutrition.Shared.ValueObjects.MacroValueObject", "ActiveGoal", b1 =>
                        {
                            b1.Property<int>("NutritionProfileUserId")
                                .HasColumnType("int");

                            b1.Property<int>("CarbG")
                                .HasColumnType("int")
                                .HasColumnName("ActiveGoal_CarbG");

                            b1.Property<int>("FatG")
                                .HasColumnType("int")
                                .HasColumnName("ActiveGoal_FatG");

                            b1.Property<int>("Kcal")
                                .HasColumnType("int")
                                .HasColumnName("ActiveGoal_Kcal");

                            b1.Property<int>("ProteinG")
                                .HasColumnType("int")
                                .HasColumnName("ActiveGoal_ProteinG");

                            b1.HasKey("NutritionProfileUserId");

                            b1.ToTable("NutritionProfiles");

                            b1.WithOwner()
                                .HasForeignKey("NutritionProfileUserId");
                        });

                    b.Navigation("ActiveGoal");
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.DiaryDay", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
