// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShapeUp.Features.Nutrition.Infrastructure.Data;

#nullable disable

namespace ShapeUp.Features.Nutrition.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    partial class NutritionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.DiaryDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EvaluatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("DiaryDays");
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.DiaryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("DiaryDayId")
                        .HasColumnType("int");

                    b.Property<string>("FoodId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("QuantityGramsOrMl")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("UsesOverride")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DiaryDayId");

                    b.ToTable("DiaryEntries");
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.NutritionGoalEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GoalMet")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("GoalEvaluations");
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.NutritionProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BiologicalSex")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("int");

                    b.Property<bool>("OnboardingSkipped")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.WeightRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("WeightRegisters");
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.WeightTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("TargetWeight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("WeightTargets");
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.DiaryEntry", b =>
                {
                    b.HasOne("ShapeUp.Features.Nutrition.Shared.Entities.DiaryDay", "DiaryDay")
                        .WithMany("Entries")
                        .HasForeignKey("DiaryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ShapeUp.Features.Nutrition.Shared.ValueObjects.MacroValueObject", "ComputedMacros", b1 =>
                        {
                            b1.Property<string>("DiaryEntryId")
                                .HasColumnType("nvarchar(24)");

                            b1.Property<int>("CarbG")
                                .HasColumnType("int")
                                .HasColumnName("ComputedMacros_CarbG");

                            b1.Property<int>("FatG")
                                .HasColumnType("int")
                                .HasColumnName("ComputedMacros_FatG");

                            b1.Property<int>("Kcal")
                                .HasColumnType("int")
                                .HasColumnName("ComputedMacros_Kcal");

                            b1.Property<int>("ProteinG")
                                .HasColumnType("int")
                                .HasColumnName("ComputedMacros_ProteinG");

                            b1.HasKey("DiaryEntryId");

                            b1.ToTable("DiaryEntries");

                            b1.WithOwner()
                                .HasForeignKey("DiaryEntryId");
                        });

                    b.Navigation("ComputedMacros")
                        .IsRequired();

                    b.Navigation("DiaryDay");
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.NutritionProfile", b =>
                {
                    b.OwnsOne("ShapeUp.Features.Nutrition.Shared.ValueObjects.MacroValueObject", "ActiveGoal", b1 =>
                        {
                            b1.Property<int>("NutritionProfileUserId")
                                .HasColumnType("int");

                            b1.Property<int>("CarbG")
                                .HasColumnType("int")
                                .HasColumnName("ActiveGoal_CarbG");

                            b1.Property<int>("FatG")
                                .HasColumnType("int")
                                .HasColumnName("ActiveGoal_FatG");

                            b1.Property<int>("Kcal")
                                .HasColumnType("int")
                                .HasColumnName("ActiveGoal_Kcal");

                            b1.Property<int>("ProteinG")
                                .HasColumnType("int")
                                .HasColumnName("ActiveGoal_ProteinG");

                            b1.HasKey("NutritionProfileUserId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("NutritionProfileUserId");
                        });

                    b.Navigation("ActiveGoal");
                });

            modelBuilder.Entity("ShapeUp.Features.Nutrition.Shared.Entities.DiaryDay", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
