using ShapeUp.Features.Nutrition.MealPlans.Shared.ViewModels;

namespace ShapeUp.Features.Nutrition.MealPlans.CreateMealPlan;

/// <summary>
/// <paramref name="TargetUserId"/> absent = the logged user; present = a plan prescribed for a client.
/// <paramref name="Id"/> is an optional client-generated plan id (24 hex chars, Mongo ObjectId format) that makes a
/// resend idempotent: the same id for the same owner returns the existing plan, another owner's id is a 409.
/// Absent = generated by the server.
/// </summary>
public record CreateMealPlanCommand(string Name, MealPlanItemInputDto[] Items,
    int? TargetUserId = null, string? Id = null);
