// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShapeUp.Features.GymManagement.Infrastructure.Data;

#nullable disable

namespace ShapeUp.Features.GymManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GymManagementDbContext))]
    [Migration("20260326215647_AddPlatformTierTargetRole")]
    partial class AddPlatformTierTargetRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("PlatformTierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PlatformTierId");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.GymClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<int>("GymPlanId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymPlanId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("GymId", "UserId")
                        .IsUnique();

                    b.ToTable("GymClients");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.GymPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("GymPlans");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.GymStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "UserId")
                        .IsUnique();

                    b.ToTable("GymStaff");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.PlatformTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxClients")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTrainers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TargetRole")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlatformTiers");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.TrainerClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerPlanId");

                    b.HasIndex("TrainerId", "ClientId")
                        .IsUnique();

                    b.ToTable("TrainerClients");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.TrainerPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerPlans");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.UserPlatformRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PlatformTierId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlatformTierId");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("UserPlatformRoles");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.Gym", b =>
                {
                    b.HasOne("ShapeUp.Features.GymManagement.Shared.Entities.PlatformTier", "PlatformTier")
                        .WithMany()
                        .HasForeignKey("PlatformTierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlatformTier");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.GymClient", b =>
                {
                    b.HasOne("ShapeUp.Features.GymManagement.Shared.Entities.Gym", "Gym")
                        .WithMany("Clients")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShapeUp.Features.GymManagement.Shared.Entities.GymPlan", "GymPlan")
                        .WithMany()
                        .HasForeignKey("GymPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShapeUp.Features.GymManagement.Shared.Entities.GymStaff", "Trainer")
                        .WithMany("AssignedClients")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gym");

                    b.Navigation("GymPlan");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.GymPlan", b =>
                {
                    b.HasOne("ShapeUp.Features.GymManagement.Shared.Entities.Gym", "Gym")
                        .WithMany("Plans")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.GymStaff", b =>
                {
                    b.HasOne("ShapeUp.Features.GymManagement.Shared.Entities.Gym", "Gym")
                        .WithMany("Staff")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.TrainerClient", b =>
                {
                    b.HasOne("ShapeUp.Features.GymManagement.Shared.Entities.TrainerPlan", "TrainerPlan")
                        .WithMany("Clients")
                        .HasForeignKey("TrainerPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainerPlan");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.UserPlatformRole", b =>
                {
                    b.HasOne("ShapeUp.Features.GymManagement.Shared.Entities.PlatformTier", "PlatformTier")
                        .WithMany()
                        .HasForeignKey("PlatformTierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlatformTier");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.Gym", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Plans");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.GymStaff", b =>
                {
                    b.Navigation("AssignedClients");
                });

            modelBuilder.Entity("ShapeUp.Features.GymManagement.Shared.Entities.TrainerPlan", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
