// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShapeUp.Features.Gamification.Infrastructure.Data;

#nullable disable

namespace ShapeUp.Features.Gamification.Infrastructure.Migrations
{
    [DbContext(typeof(GamificationDbContext))]
    partial class GamificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShapeUp.Features.Gamification.Shared.Entities.GamificationProfile", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastActivityDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastEvaluationLevelFrom")
                        .HasColumnType("int");

                    b.Property<int?>("LastEvaluationLevelTo")
                        .HasColumnType("int");

                    b.Property<bool>("LastEvaluationLeveledUp")
                        .HasColumnType("bit");

                    b.Property<bool>("LastEvaluationStreakMilestoneHit")
                        .HasColumnType("bit");

                    b.Property<int?>("LastEvaluationStreakMilestoneValue")
                        .HasColumnType("int");

                    b.Property<int>("LastStreakMilestoneAwarded")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("ShapeCoins")
                        .HasColumnType("int");

                    b.Property<int>("TotalXp")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ShapeUp.Features.Gamification.Shared.Entities.WorkoutEvaluation", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("Classification")
                        .HasColumnType("int");

                    b.Property<bool>("CreditGranted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId", "EvaluatedAtUtc");

                    b.ToTable("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
